post:
      summary: Crea un nuevo proyecto
      tags: [Project]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                status:
                  type: string
      responses:
        201:
          description: Proyecto creado
get:
      summary: Obtiene todos los proyectos
      tags: [Project]
      responses:
        200:
          description: Lista de proyectos

