openapi: 3.0.0
info:
  title: Developer Social Network API
  version: 1.0.0
  description: Documentación de la API usando Swagger
servers:
  - url: https://mrmolanodev.site/api/v1
    description: Production server
  - url: http://localhost:3000/api/v1
    description: Sandbox server (uses test data)
tags:
  - name: Posts
    description: API para gestionar posts
  - name: Project
    description: API para gestionar projects
  - name: Authentication
    description: API para autenticar usuarios
  - name: Users
    description: API para gestionar usuarios
  - name: Technologies
    description: API para gestionar tecnologias
  - name: Comment
    description: API para gestionar comentarios
paths:
  /post:
    $ref: './paths/post.yaml'
  /post/{id}:
    $ref: './paths/post-by-id.yaml'
  /post/user/{userid}:
    $ref: './paths/post-user.yaml'
  /project:
    $ref: './paths/project.yaml'
  /project/{id}:
    $ref: './paths/project-by-id.yaml'
  /technology:
    $ref: './paths/technology.yaml'
  /technology/{name}:
    $ref: './paths/technology-by-name.yaml'
  /user:
    $ref: './paths/user.yaml'
  /user/{id}:
    $ref: './paths/user-by-id.yaml'
  /comment:
    $ref: './paths/comment.yaml'
  /comment/{id}:
    $ref: './paths/comment-by-id.yaml'
  /auth/register:
    $ref: './paths/register.yaml'
  /auth/login:
    $ref: './paths/login.yaml'
  /auth/me:
    $ref: './paths/login.yaml'
  /like/user/{userid}:
    $ref: './paths/user-like.yaml'
