openapi: 3.0.0
info:
  title: Developer Social Network API
  version: 1.0.0
  description: Documentación de la API usando Swagger
servers:
  - url: http://ec2-100-25-217-101.compute-1.amazonaws.com
    description: Production server
  - url: http://localhost:3000/api/v1
    description: Sandbox server (uses test data)
tags:
  - name: Posts
    description: API para gestionar posts
  - name: Project
    description: API para gestionar projects
  - name: Authentication
    description: API para autenticar usuarios
paths:
  /post:
    $ref: './paths/post.yaml'
  /post/{id}:
    $ref: './paths/post-by-id.yaml'
  /project:
    $ref: './paths/project.yaml'
  /project/{id}:
    $ref: './paths/project-by-id.yaml'
  /technology:
    $ref: './paths/technology.yaml'
  /technology/{name}:
    $ref: './paths/technology-by-name.yaml'
  /auth/register:
    $ref: './paths/register.yaml'
  /auth/login:
    $ref: './paths/login.yaml'
